JW-1199: Check if extension is running after enabling
codilime/contrail-windows-docker pull request #102
Opened 2017-10-13 10:42 UTC by krdln

2017-10-13 10:43 UTC, krdln commented
Not sure about the error message.

Should I add a comment about it being a workaround for some windows/extension bug?

2017-10-13 11:02 UTC, m-kostrzewa commented
> Should I add a comment about it being a workaround for some windows/extension bug?

steps to repro maybe?

2017-10-13 11:02 UTC, krdln commented
@m-kostrzewa They're in jira ticket

2017-10-13 11:03 UTC, m-kostrzewa commented
We probably should add a test case that shows steps to repro and asserts that driver init fails

2017-10-13 11:31 UTC, jablonskim approved these changes

2017-10-13 12:19 UTC, mclapinski requested changes

2017-10-13 12:19 UTC, michal-clapinski commented on driver/driver.go
> +			return errors.New("Extension stopped running after enable. " +
should be `after being enabled`

2017-10-18 15:10 UTC, mclapinski approved these changes

2017-10-19 11:23 UTC, merged