JW-63 Duplicate values in system PATH
codilime/contrail-windows-docker pull request #20
Opened 2017-01-11 12:13 UTC by mmasztalerczuk

-> Added removing duplicated values
  -> Removed problem with not existing 'vendor' branch
  -> Some small changes during git instalation

2017-01-11 12:26 UTC, m-kostrzewa requested changes
use echo, otherwise approve

2017-01-11 12:26 UTC, m-kostrzewa commented on ci/install_git.ps1
> +Write-Host ""
I think we should stick to echo or Write-Host.

2017-01-11 12:45 UTC, mmasztalerczuk commented
I replace _Write-Host_ in one place, but I need _Write-Host_ because _echo_ can't set color and write to input without new line char.

2017-01-11 13:08 UTC, m-kostrzewa commented
ok

2017-01-11 13:08 UTC, m-kostrzewa approved these changes

2017-01-13 13:53 UTC, Attil approved these changes

2017-01-17 11:37 UTC, unya commented
LGTM. Merging

2017-01-17 11:37 UTC, merged