HNS endpoint operations wrapper and tests.
codilime/contrail-windows-docker pull request #21
Opened 2017-01-11 14:22 UTC by m-kostrzewa

Simple wrapper for HNS endpoint management + tests.

2017-01-12 10:20 UTC, sodar approved these changes

2017-01-13 13:51 UTC, Attil requested changes

2017-01-13 13:51 UTC, Attil commented on hns/hns_test.go
> +					RemoveVolumes: true,
Are there any volumes? I don't think there are created any.
If it's to be future-proof consider adding also RemoveLinks.

2017-01-13 13:51 UTC, Attil commented on hns/hns_test.go
> +				r, err := docker.ContainerCreate(context.Background(),
Without any network?

2017-01-16 14:27 UTC, m-kostrzewa commented
@Attil Your comments made me realize that docker isn't needed for these tests and was just dead code. Removed it. Please re-review.

2017-01-17 10:32 UTC, Attil approved these changes

2017-01-17 10:34 UTC, merged