[WIP] Test on actual controller
codilime/contrail-windows-docker pull request #23
Opened 2017-01-13 17:42 UTC by m-kostrzewa

2017-01-16 14:25 UTC, m-kostrzewa commented on controller/controller.go
> +	// TODO: use environment variables for keystone auth
https://codilime.atlassian.net/browse/JW-66

2017-01-16 14:46 UTC, sodar approved these changes
Looks good

2017-01-17 13:27 UTC, mmasztalerczuk requested changes

2017-01-17 13:27 UTC, mmasztalerczuk commented on controller/controller.go
> +	keystone := contrail.NewKeystoneClient("http://10.7.0.54:5000/v2.0", "admin", "admin",
I think that you should use here not hard-coded values, but variables. Also, add 'JW-66' to TODO comment.

2017-01-17 13:27 UTC, mmasztalerczuk commented on controller/controller.go
>  	if err == nil && instance != nil {
What if err is not nil?

2017-01-17 13:27 UTC, mmasztalerczuk commented on controller/controller_test.go
> +	flag.IntVar(&controllerPort, "controllerPort", 8082, "Contrail controller port")
More hard-coded value.

2017-01-17 13:27 UTC, mmasztalerczuk commented on controller/controller.go
I'm not sure, but what about copyrights?

2017-01-17 14:37 UTC, m-kostrzewa commented on controller/controller_test.go
> +	flag.IntVar(&controllerPort, "controllerPort", 8082, "Contrail controller port")
This isn't hardcoded, these are default values for command line options

2017-01-17 14:52 UTC, m-kostrzewa commented on controller/controller.go
you mean Juniper code? Pretty sure we can use it

2017-01-17 14:54 UTC, m-kostrzewa commented on controller/controller.go
>  	if err == nil && instance != nil {
err == nil && instance != nil means that an existing machine was found - so we return it. Else, we create a new one

2017-01-17 15:03 UTC, mmasztalerczuk approved these changes

2017-01-17 15:04 UTC, m-kostrzewa commented on controller/controller.go
>  	if err == nil && instance != nil {
JW-84

2017-01-17 15:04 UTC, merged