Fix instance IP allocation.
codilime/contrail-windows-docker pull request #31
Opened 2017-01-31 19:27 UTC by m-kostrzewa

Instance IP and other objects are now allocated correctly in Contrail.

2017-02-01 15:10 UTC, mclapinski requested changes

2017-02-01 15:10 UTC, michal-clapinski commented on controller/controller_test.go
> +				Expect(instanceIP.GetInstanceIpAddress()).ToNot(Equal(""))
You have already checked this in line 264 so looks useless to me.

2017-02-01 15:33 UTC, m-kostrzewa commented
Fix'd, LGTY? @michal-clapinski

2017-02-01 15:42 UTC, mclapinski approved these changes

2017-02-02 10:37 UTC, mmasztalerczuk commented on controller/controller.go
> +		return nil, err
Maybe print error log here?

2017-02-02 10:37 UTC, mmasztalerczuk commented on controller/controller.go
> +		return nil, err
Add error log here.

2017-02-02 10:37 UTC, mmasztalerczuk commented on controller/controller.go
> +		return nil, err
Add error log here.

2017-02-02 10:37 UTC, mmasztalerczuk commented on controller/controller_test.go
> +				Expect(instanceIP.GetInstanceIpAddress()).ToNot(Equal(""))
Why are you checking not empty string? Maybe Expect(instanceIP.GetInstanceIpAddress()).To(Equal(testInstanceIP.GetInstanceIpAddress())) ?

2017-02-02 10:37 UTC, mmasztalerczuk commented on controller/controller_test.go
>  				Expect(existingIP.GetUuid()).To(Equal(instanceIP.GetUuid()))
Why did you not check ip here? Checking Uuid is enough? (if yes, why are you checking not empty string in 263 line)

2017-02-02 10:56 UTC, m-kostrzewa commented on controller/controller_test.go
>  				Expect(existingIP.GetUuid()).To(Equal(instanceIP.GetUuid()))
I don't know what IP will contrail allocate for us

2017-02-02 11:00 UTC, mmasztalerczuk approved these changes

2017-02-02 11:01 UTC, merged