JW-43 (docker api) Handle create requests
codilime/contrail-windows-docker pull request #32
Opened 2017-02-06 16:00 UTC by m-kostrzewa

Big PR because the functionality was pretty entangled and required some changes to HNS and controller handling.

Also, updated vendors because improved test framework.

- [ ] JW-44 Handle network create in Contrail
- [ ] JW-45 Handle endpoint create in Contrail
- [ ] JW-149 Handle network create in HNS
- [ ] JW-151 Handle endpoint create in HNS

bonus (needed it for end to end tests so I include it in this PR): 
- [ ] JW-190 driver should stop on Ctrl+C

Also, there is some logic on Deleting networks and endpoints, but JW-150 and JW-152 are not done yet. I needed some deletion logic to cleanup between tests.

2017-02-06 18:09 UTC, sodar requested changes

2017-02-06 18:09 UTC, sodar commented on driver/driver.go
> +	if err != nil {
Assignment to `err` omitted when calling `hnsMgr.DeleteNetwork`.

2017-02-06 18:09 UTC, sodar commented on driver/driver_test.go
> +								Expect(err).ToNot(HaveOccurred())
This case is tested twice (here and in "removed HNS set" above). Is it necessary?

2017-02-06 18:09 UTC, sodar commented on driver/driver_test.go
> +									// don't clean up endpoints that weren't created during tests.
I think that this loop will delete more HNS endpoints than it should.

Let's say `endpointsBefore := [A, B]` and `endpoints := [A, B, C]`. Then on first iteration of outer loop, that is when`e := A`, `A` will be removed, because when `originalEndpoint := B`, then delete endpoint function will be called, but it shouldn't be called because `A` belongs to `endpointBefore`.

2017-02-06 18:09 UTC, sodar commented on driver/driver_test.go
> +								if _, exists := resp.NetworkSettings.Networks[networkName]; exists {
I do not understand this condition. `ep` and `networkName` seem to be unrelated here, because `ep` is not used in this condition when looping over endpoints. Could you elaborate what needs to be done here?

2017-02-06 18:16 UTC, m-kostrzewa commented on driver/driver_test.go
> +								if _, exists := resp.NetworkSettings.Networks[networkName]; exists {
> Could you elaborate what needs to be done here?

no, i screwed up

2017-02-07 11:01 UTC, sodar approved these changes

2017-02-07 13:08 UTC, Attil requested changes

2017-02-07 13:08 UTC, Attil commented on ci/clone_and_test.ps1
> +go get -u github.com/onsi/ginkgo/ginkgo
Are you sure always updating everything is a good idea? If some API-breaking change happens then everything would break.

2017-02-07 13:08 UTC, Attil commented on common/config.go
> +	return ([]string{filepath.Join(os.Getenv("programdata"), "docker", "plugins")})[0]
This is very redundant. For proof, see [this code I wrote](https://play.golang.org/p/Kwhy392FDI).

2017-02-07 13:08 UTC, Attil commented on common/misc.go
> +		log.Debugln("Could not remove container network.")
Shouldn't you return an error here?

2017-02-07 13:08 UTC, Attil commented on common/misc.go
>  		log.Debugln("Could not remove container network.")
Shouldn't you return an error here?

2017-02-07 13:08 UTC, Attil commented on common/misc.go
>  		"C:\\ProgramData\\Microsoft\\Windows\\HNS\\HNS.data").Run(); err != nil {
`filepath.Join` and directory should be derived from an env variable. Right now, this code won't work if someone installed Windows on D: drive for example.

2017-02-07 13:08 UTC, Attil commented on controller/controller.go
> +		return nil, errors.New("Ipam subnets list is empty")
You very often type an error string twice. Maybe some function could reduce code repetition?

2017-02-07 13:08 UTC, Attil commented on driver/driver.go
> +	if err := os.MkdirAll(common.PluginSpecDir(), 0755); err != nil {
Execute/read permission for others?

2017-02-07 13:08 UTC, Attil commented on driver/driver.go
> +	time.Sleep(time.Second * 1)
Are you sure this is the correct way to do this? Maybe some variable shared with the goroutine above?

2017-02-07 13:08 UTC, Attil commented on driver/driver.go
> +		return errors.New("Generic options missing")
Sometimes you print before returning a new error and sometime you do not. I suggest choosing one way for consistency and sticking to it.

2017-02-07 13:08 UTC, Attil commented on driver/driver.go
> +		DisableGatewayService: true,
If you disable gateway, what is the point of giving a gateway address there?

2017-02-07 13:20 UTC, mmasztalerczuk requested changes

2017-02-07 13:20 UTC, mmasztalerczuk commented on common/misc.go
>  		log.Debugln("Could not remove container network.")
What if Remove-ContainerNetwork fails? Not any action? Only debug log?

2017-02-07 13:20 UTC, mmasztalerczuk commented on common/misc.go
>  	log.Debugln("Removing HNS program data")
What is Stop-Service don't stop hns? (My comment is to line 24-25)

2017-02-07 13:20 UTC, mmasztalerczuk commented on common/misc.go
>  		"C:\\ProgramData\\Microsoft\\Windows\\HNS\\HNS.data").Run(); err != nil {
Add to const?

2017-02-07 13:20 UTC, mmasztalerczuk commented on driver/driver.go
> +func NewDriver(adapter string, c *controller.Controller) (*ContrailDriver, error) {
Error is never returned. Maybe remove it from prototype?

2017-02-07 13:20 UTC, mmasztalerczuk commented on driver/driver_test.go
> +	err = common.RestartDocker()
Why are you restart docker after finish suit? Why not disable?

2017-02-07 13:20 UTC, mmasztalerczuk commented on driver/driver_test.go
> +		d, err := sockets.DialPipe("//./pipe/"+common.DriverName, time.Second*3)
time.Second*3 ? Why? Maybe constant for that?

2017-02-07 13:20 UTC, mmasztalerczuk commented on driver/driver_test.go
> +						NetworkID: "MyAwesomeNet",
Constant

2017-02-07 13:20 UTC, mmasztalerczuk commented on driver/driver_test.go
> +			PContext("on AllocateNetwork", func() {
Spaces/tabs

2017-02-07 13:20 UTC, mmasztalerczuk commented on driver/driver_test.go
> +								"network": "lolel",
constant

2017-02-07 13:48 UTC, m-kostrzewa commented on ci/clone_and_test.ps1
> +go get -u github.com/onsi/ginkgo/ginkgo
This is just test framework, not some dependency. All deps are frozen in vendors dir anyways.

2017-02-07 13:48 UTC, m-kostrzewa commented on common/config.go
> +	return ([]string{filepath.Join(os.Getenv("programdata"), "docker", "plugins")})[0]
Yeah, this is left-over from old plugin impl. Will fix

2017-02-07 15:03 UTC, m-kostrzewa commented on common/misc.go
> +		log.Debugln("Could not remove container network.")
no, I want to keep going with cleanup procedure. If Get-ContainerNetwork or Get-NetNat etc fails, maybe removing hns database will work.

2017-02-07 15:03 UTC, m-kostrzewa commented on common/misc.go
>  		log.Debugln("Could not remove container network.")
see above

2017-02-07 15:09 UTC, m-kostrzewa commented on driver/driver.go
> +	if err := os.MkdirAll(common.PluginSpecDir(), 0755); err != nil {
Not sure on this, I have PR to docker/go-plugins-helpers, where it's been discussed. In any case, this is how it's done on Unix.

2017-02-07 15:10 UTC, m-kostrzewa commented on driver/driver.go
> +	time.Sleep(time.Second * 1)
How would that help? Still, you would need to make sure that variable is changed atomically with listener starting to serve.

2017-02-07 15:16 UTC, m-kostrzewa commented on common/misc.go
>  		log.Debugln("Could not remove container network.")
see my response to @Attil

2017-02-07 15:21 UTC, m-kostrzewa commented on driver/driver_test.go
> +	err = common.RestartDocker()
I think this is in some commit in the middle? I think this is fixed in next commits

2017-02-07 15:21 UTC, m-kostrzewa commented on driver/driver_test.go
> +		d, err := sockets.DialPipe("//./pipe/"+common.DriverName, time.Second*3)
In test code, it's better to have stuff like this explicit

2017-02-07 15:22 UTC, m-kostrzewa commented on driver/driver_test.go
> +		d, err := sockets.DialPipe("//./pipe/"+common.DriverName, time.Second*3)
Actually this applies to other comments as well. In test code, it's often better to not use constants of variables as test data.

2017-02-07 15:23 UTC, m-kostrzewa commented on driver/driver_test.go
> +	err = common.RestartDocker()
(it's moved to BeforeSuite)

2017-02-07 15:24 UTC, m-kostrzewa commented on driver/driver_test.go
> +			PContext("on AllocateNetwork", func() {
sorry I don't see what you mean?

2017-02-07 15:38 UTC, m-kostrzewa commented on driver/driver.go
> +		DisableGatewayService: true,
This is done similarly to https://github.com/docker/libnetwork/blob/master/drivers/windows/windows.go#L640

2017-02-07 15:40 UTC, m-kostrzewa commented on common/misc.go
>  	log.Debugln("Removing HNS program data")
I don't think this is possible. If service missbehaves, I think Windows kills it?

2017-02-07 15:40 UTC, m-kostrzewa commented on common/misc.go
>  		"C:\\ProgramData\\Microsoft\\Windows\\HNS\\HNS.data").Run(); err != nil {
Actually I use programdata env variable now, as @attil asked

2017-02-07 16:11 UTC, m-kostrzewa commented on driver/driver.go
> +		return errors.New("Generic options missing")
Not really. If I return request to docker daemon, I don't log errorsbecause docker daemon will do it for me. Else, I log errors.

2017-02-08 09:50 UTC, Attil requested changes

2017-02-08 09:50 UTC, Attil commented on common/misc.go
> +		log.Debugln("Could not remove nat network.")
You are removing every container network existing on the machine, not just the NAT one.

2017-02-08 09:50 UTC, Attil commented on common/misc.go
> +		return errors.New("Invalid program data env variable")
Duplicated string.

2017-02-08 11:39 UTC, mmasztalerczuk approved these changes

2017-02-08 11:39 UTC, mmasztalerczuk commented on hns/hns_test.go
> +	err = common.HardResetHNS()
Why are you restarting this twice?

2017-02-08 11:39 UTC, mmasztalerczuk commented on hns/hns_test.go
>  			}
Maybe other word? ;)

2017-02-08 11:39 UTC, mmasztalerczuk commented on driver/driver_test.go
> +			PContext("on AllocateNetwork", func() {
I thought that github shows mixed tab and spaces, but no. It is ok.

2017-02-08 11:39 UTC, mmasztalerczuk commented on driver/driver_test.go
> +		d, err := sockets.DialPipe("//./pipe/"+common.DriverName, time.Second*3)
I disagree that value should be explicit in test code. What if I want to test this with time.second*5? or 10? Should I updated this in every place?

2017-02-08 11:47 UTC, m-kostrzewa commented on hns/hns_test.go
> +	err = common.HardResetHNS()
This is leftover from that weird bug where every second test would fail. This seems to be fixed now, so this is dead code.

2017-02-08 12:39 UTC, Attil approved these changes

2017-02-08 12:39 UTC, merged