Implement basic tests. Change project hierarchy.
codilime/contrail-windows-docker pull request #5
Opened 2016-12-12 15:43 UTC by m-kostrzewa

2016-12-16 16:03 UTC, Attil requested changes

2016-12-16 16:03 UTC, Attil commented on main.go
> +		SecurityDescriptor: "S:(ML;;NW;;;LW)D:(A;;0x12019f;;;WD)",
IMO not everyone should have these permissions.

2016-12-16 16:03 UTC, Attil commented on tests/driver_test.go
> +			})
It should check whether the network was allocated.

2016-12-16 16:03 UTC, Attil commented on tests/driver_test.go
> +				Expect(err).ShouldNot(HaveOccurred())
It should check whether the network was deleted.

2016-12-16 16:03 UTC, Attil commented on tests/driver_test.go
> +				Expect(err).ShouldNot(HaveOccurred())
It should check whether the network was freed.

2016-12-16 16:03 UTC, Attil commented on tests/driver_test.go
> +			})
It should check whether the endpoint exists.

2016-12-16 16:03 UTC, Attil commented on tests/driver_test.go
> +			})
It should check whether the endpoint was deleted.

2016-12-16 16:03 UTC, Attil commented on tests/driver_test.go
> +				It("responds with proper JoinResponse, nil", func() {}) // nil maybe?
Check whether the endpoint left (the network?).

2016-12-19 11:25 UTC, m-kostrzewa commented on main.go
> +		SecurityDescriptor: "S:(ML;;NW;;;LW)D:(A;;0x12019f;;;WD)",
I'm not sure what they should be, let's create an issue for this and fix in another PR

2016-12-19 11:28 UTC, m-kostrzewa commented
TBH i think this PR can be closed since https://github.com/codilime/contrail-windows-docker/pull/6 contains it

2016-12-28 12:38 UTC, closed without merging

2016-12-28 12:40 UTC, m-kostrzewa commented on tests/driver_test.go
> +			})
All these change request are about non-existing features, they will be added in another pr.