JW-330 Pipe access denied
codilime/contrail-windows-docker pull request #76
Opened 2017-03-27 12:40 UTC by m-kostrzewa

Attempts to fix this problem:

http://ci.wincontrail.codilime.com:8080/job/Wincontrail/job/test-integration/433/testReport/(root)/Contrail%20Network%20Driver%20test%20suite/On_requests_from_docker_daemon_on_CreateNetwork_request_with_different__invalid_options_subnet_doesn_t_exist_in_Contrail/

Note, that we use the following construction to wait for our serve goroutine to spin up:

```
	startedServing := make(chan interface{}, 1)
	go func() {
		startedServing <- 1
		h.Serve(d.listener)
	}()
	// wait for listener goroutine to spin up before moving on. Note: this is not entirely
	// thread safe, but I tried other ways to do it and was not successful.
	<-startedServing
```

which is NOT thread safe. Threads may switch in-between ```startedServing <- 1``` and ```h.Serve(d.listener)```.

Normally, the handler (```h``` in the above) should implement something like "is started" channel or method, but I don't feel like modifying even more 3rd party packages... This would involve modifying microsoft/go-winio and/or docker/go-plugins-helpers.

Nonetheless, it seems that it actually fixed the problem, at least to a high degree, as I can't reproduce the original issue.

2017-03-27 12:51 UTC, m-kostrzewa commented
Janie, przetestuj proszę

2017-03-27 14:33 UTC, m-kostrzewa commented
Janie, przetestuj proszę

2017-03-27 17:04 UTC, m-kostrzewa commented
Janie, przetestuj proszę

2017-03-28 14:28 UTC, m-kostrzewa commented
Janie, przetestuj proszę

2017-03-28 17:09 UTC, m-kostrzewa commented
Janie, przetestuj proszę

2017-03-28 17:29 UTC, m-kostrzewa commented
Janie, przetestuj proszę

2017-03-29 06:24 UTC, m-kostrzewa commented
Janie, przetestuj proszę

2017-03-29 14:48 UTC, m-kostrzewa commented
Janie, przetestuj proszę

2017-03-29 14:50 UTC, m-kostrzewa commented
Running tests again to make sure

2017-03-29 16:38 UTC, mclapinski approved these changes
Congrats on making tests pass

2017-03-29 16:38 UTC, michal-clapinski commented on driver/driver_test.go
> +		conn, err := sockets.DialPipe("//./pipe/"+common.DriverName, timeout)
Can't you reuse ```d.pipeAddr```?

2017-03-29 16:38 UTC, michal-clapinski commented on driver/driver_test.go
> +		conn, err = sockets.DialPipe("//./pipe/"+common.DriverName, timeout)
Same as above

2017-03-30 08:45 UTC, Attil requested changes

2017-03-30 08:45 UTC, Attil commented on driver/driver.go
> +	// wait for listener goroutine to spin up before moving on. Note: this is not entirely
If this is not completely thread safe, why not use a mutex?

2017-03-30 08:45 UTC, Attil commented on driver/driver.go
> +func (d *ContrailDriver) createRootNetwork() error {
What *is* a root network and why do we need it?

2017-03-30 08:45 UTC, Attil commented on driver/driver.go
> +func (d *ContrailDriver) waitForPipe(waitUntilExists bool) error {
`waitUntilExits` is conventionally called 'blocking'.

2017-03-30 08:45 UTC, Attil commented on driver/driver_test.go
> +		if conn != nil {
Is there a possibility of both following statements being true at once?
* `conn` being `nil`
* `err` not occuring

2017-03-30 08:45 UTC, Attil commented on driver/driver_test.go
> +		cleanupAllDockerNetworksAndContainers(docker)
BTW. Now that I think about it, you should probably only delete containers and networks created during the test, not all of them.

2017-03-30 08:51 UTC, m-kostrzewa commented on driver/driver.go
> +func (d *ContrailDriver) waitForPipe(waitUntilExists bool) error {
This is a typo, should be "waitUntilExists"

2017-03-30 08:52 UTC, m-kostrzewa commented on driver/driver.go
> +	// wait for listener goroutine to spin up before moving on. Note: this is not entirely
It's impossible, since h.Serve() is blocking. Also, chan interface{} is mutex

2017-03-30 09:03 UTC, Attil commented on driver/driver.go
> +func (d *ContrailDriver) waitForPipe(waitUntilExists bool) error {
Please add some comments, what is exactly the point of this function and how it should work.

2017-03-30 11:48 UTC, m-kostrzewa commented
Janie, przetestuj proszę

2017-03-30 17:10 UTC, m-kostrzewa commented
This change to go-winio seems to have fixed the problem with nil pointer dereference encountered here: http://ci.wincontrail.codilime.com:8080/job/Wincontrail/job/test-integration/489/console

https://github.com/Microsoft/go-winio/pull/45

Please re-review

2017-03-30 23:24 UTC, m-kostrzewa commented
This passed. Running again.

2017-03-30 23:24 UTC, m-kostrzewa commented
Janie, przetestuj proszę

2017-03-31 13:59 UTC, Attil approved these changes

2017-03-31 14:03 UTC, merged